# Appspec.yml file for aws code Deploy deployment

version: 0.0
os: linux
files:
  - source: app/back-end
    destination: /var/www/back-end
    overwrite: true

hooks:
  ApplicationStop:
    - location: app/back-end/scripts/stop_server.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: app/back-end/scripts/before_script.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: app/back-end/scripts/after_script.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: app/back-end/scripts/start_server.sh
      timeout: 300
      runas: root
