version: 0.0
os: linux
files:
  - source: /app/back-end
    destination: /home/readrack/back-end

hooks:
  BeforeInstall:
    - location: scripts/before_script.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/after_script.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_docker.sh
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/stop_docker.sh
      timeout: 300
      runas: root
