version: 0.0
os: linux
files:
  - source: app/back-end
    destination: /app/back-end
    overwrite: true

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/before_script.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/after_script.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
